2.x Remove Function from transformer interfaces to allow a single obj…
ReactiveX/RxJava pull request #4672
Opened 2016-10-05 18:48 UTC by dalewking

This pull request removes Function from the super type of the various Transformer interfaces. While these are technically functions, the problem is that if they all extend Function then you cannot have a single object instance that can implement multiple Transformer interfaces. The goal is to be able to call a function that returns an object that can be passed to Observable.compose or Single.Compose and so on.

This was an issue with RxLifecycle project. See this for more info: https://github.com/trello/RxLifecycle/issues/39

2016-10-05 18:58 UTC, akarnokd requested changes

2016-10-05 18:58 UTC, akarnokd commented on src/main/java/io/reactivex/FlowableTransformer.java
> +    Publisher<? extends Downstream> apply(Flowable<Upstream> flowable);
We should avoid covariant return types (drop `? extends`).

2016-10-05 18:58 UTC, akarnokd commented on src/main/java/io/reactivex/Maybe.java
> +            return wrap(transformer.apply(this));
There is no need to try-catch it if it doesn't declare `throws Exception`. So either each transformer should specify `apply(...) throws Exception` or these are not needed.

2016-10-05 18:58 UTC, akarnokd commented on src/main/java/io/reactivex/FlowableTransformer.java
> +    Publisher<? extends Downstream> apply(Flowable<Upstream> flowable) throws Exception;
`? extends` should be removed as covariant return types are usually inconvenience to the consumer.

2016-10-05 19:00 UTC, dalewking commented on src/main/java/io/reactivex/FlowableTransformer.java
> +    Publisher<? extends Downstream> apply(Flowable<Upstream> flowable);
It was there before in the code I changed, so I left it there. Whether it should be there or not is orthogonal to this request

2016-10-05 19:00 UTC, akarnokd commented
/cc @JakeWharton

2016-10-05 19:03 UTC, akarnokd commented on src/main/java/io/reactivex/FlowableTransformer.java
> +    Publisher<? extends Downstream> apply(Flowable<Upstream> flowable);
This is also an opportunity to fix the signatures, saves 1 PR.

2016-10-05 19:06 UTC, dalewking commented
Another cleanup is that some of the compose methods use paramater name transformer and some use composer, should settle on one or the other.

2016-10-05 19:37 UTC, dalewking commented on src/main/java/io/reactivex/FlowableTransformer.java
> +    Publisher<? extends Downstream> apply(Flowable<Upstream> flowable);
I am not certain whether the ? extends should be there or not. I know that I have long had generic type problems with compose and RxLifecycle and am not sure whether the fault is RxJava or RxLifecycle. And the results vary between Java7, Java 8, and Kotlin regarding this.

See this discussion in RxLifecycle: https://github.com/trello/RxLifecycle/issues/58

2016-10-05 19:38 UTC, dalewking commented on src/main/java/io/reactivex/Maybe.java
> +            return wrap(transformer.apply(this));
It does throw exception see later commit

2016-10-05 19:40 UTC, akarnokd approved these changes

2016-10-06 00:07 UTC, hzsweers commented
What's the reasoning for the exception in the signatures?

2016-10-06 01:33 UTC, dalewking commented
The reasoning for the exception was that the previous version where they implemented Function supported throwing exceptions so I wasn't trying to change the method signature (there was actually a test for it on one of the types which is why the first build failed).

For the more general reasoning for why all the functional interfaces in RxJava2 declare throws Exception see this section: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#functional-interfaces

2016-10-06 01:42 UTC, hzsweers commented
Cool, thanks for the explanation!

2016-10-06 01:45 UTC, ZacSweers approved these changes
LGTM pending resolution of the covariant return type comment

2016-10-06 10:31 UTC, vanniktech commented
Should not a unit test be added to guarantee this behavior?

2016-10-06 14:17 UTC, merged

2016-10-06 14:28 UTC, akarnokd commented
It seems I have to do that myself.

2016-10-08 10:47 UTC, vanniktech commented
How do you guys feel if all of the operators (CompletableOperator, FlowableOperator, ...) would change to this behavior too for consistency and for the same reasons @dalewking already stated.

2016-10-08 14:05 UTC, akarnokd commented
They can be standalone, just don't forget the javadoc.

2016-10-08 14:42 UTC, dalewking commented
I am also thinking about this for the "to" method by changing the XxxxxTransformer interfaces to be more general purpose and usable by both compose and to. Here is what I am suggesting as applied to Observable and if it sounds good to you I will do a PR:

The new ObservableTransformer:
```
/**
 * Interface to transform Observables, used for composing and "to" transformations.
 *
 * @param <Upstream> the upstream value type
 * @param <Result> the transformation result type
 */
public interface ObservableTransformer<Upstream, Result> {
    /**
     * Applies a function to the upstream Observable and returns a new result with
     * optionally different element type.
     * @param upstream the upstream Observable instance
     * @return the transformed result
     * @throws Exception in case the transformation throws, checked exceptions will be wrapped
     * into a RuntimeException
     */
    Result apply(Observable<Upstream> upstream) throws Exception;
}
```

compose and to methods:

    @SchedulerSupport(SchedulerSupport.NONE)
    public final <R> Observable<R> compose(ObservableTransformer<T, ObservableSource<R>> composer) {
            return wrap(to(composer));
    }

    @SchedulerSupport(SchedulerSupport.NONE)
    public final <R> R to(ObservableTransformer<T, R> converter) {
        try {
            return converter.apply(this);
        } catch (Throwable ex) {
            Exceptions.throwIfFatal(ex);
            throw ExceptionHelper.wrapOrThrow(ex);
        }
    }

2016-10-08 15:57 UTC, zhoutianxing commented
yes

2016-10-09 00:09 UTC, dalewking commented
After having tried implementing what I showed above and seeing how many changes that required in the unit test, I am not sure it is the fest approach. It may be better to introduce interfaces like ObservableFunction<T, R> which signature wise is like Function<Observable<T>, R> but not extending Function that is used for the "to" method and ObservableTransformer extends that interface, where R is ObservableSource<DownStream>. Interested in feedback.