2.x: Test static from methods and add Maybe.fromSingle & fromCompletable
ReactiveX/RxJava pull request #4685
Opened 2016-10-09 10:49 UTC by vanniktech

- add Maybe.fromSingle by reusing MaybeFromSingle
- add Maybe.fromCompletable by resuing MaybeFromCompletable
- remove anonymous classes in various operators
- add tests for
  - Completable.fromAction()
  - Completable.fromCallable()
  - Completable.fromObservable()
  - Completable.fromPublisher()
  - Completable.fromRunnable()
  - Completable.fromSingle()
  - Maybe.fromAction()
  - Maybe.fromCallable()
  - Maybe.fromCompletable()
  - Maybe.fromRunnable()
  - Maybe.fromSingle()
  - Single.fromCallable()

2016-10-09 14:10 UTC, akarnokd requested changes

2016-10-09 14:10 UTC, akarnokd commented on src/main/java/io/reactivex/internal/operators/completable/CompletableFromObservable.java
> +    static class CompletableFromObservableObserver<T> implements Observer<T> {
final

2016-10-09 14:10 UTC, akarnokd commented on src/main/java/io/reactivex/internal/operators/completable/CompletableFromObservable.java
> +    static class CompletableFromObservableObserver<T> implements Observer<T> {
sorry, didn't see the enclosing package.

2016-10-09 14:10 UTC, akarnokd commented on src/main/java/io/reactivex/internal/operators/completable/CompletableFromSingle.java
> +    static class CompletableFromSingleObserver<T> implements SingleObserver<T> {
final

2016-10-09 14:10 UTC, akarnokd commented on src/test/java/io/reactivex/internal/operators/completable/CompletableFromRunnableTest.java
> +
I'd increment a counter and assert its 1.

2016-10-09 17:48 UTC, JakeWharton commented on src/main/java/io/reactivex/Maybe.java
> +    public static <T> Maybe<T> fromCompletable(final Completable completable) {
final isn't needed. This should be CompletableSource otherwise it's redundant with toMaybe().

2016-10-09 17:48 UTC, JakeWharton commented on src/main/java/io/reactivex/Maybe.java
> +    public static <T> Maybe<T> fromSingle(final Single single) {
Ditto to both here

2016-10-09 17:48 UTC, JakeWharton commented on src/test/java/io/reactivex/internal/operators/completable/CompletableFromActionTest.java
> +
Assert with counter

2016-10-09 17:48 UTC, JakeWharton commented on src/test/java/io/reactivex/internal/operators/completable/CompletableFromCallableTest.java
> +                return null;
Assert with counter. You could return it's value and assert you only get 1 and that a subsequent call gets 2

2016-10-09 17:48 UTC, JakeWharton commented on src/test/java/io/reactivex/internal/operators/completable/CompletableFromActionTest.java
> +
And make sure second subscription increments again

2016-10-09 17:48 UTC, JakeWharton commented on src/test/java/io/reactivex/internal/operators/completable/CompletableFromRunnableTest.java
> +
Can also test calling twice increments twice. And that it calls lazily (not on creation).

2016-10-09 17:48 UTC, JakeWharton commented on src/test/java/io/reactivex/internal/operators/maybe/MaybeFromActionTest.java
> +
Same

2016-10-09 17:48 UTC, JakeWharton commented on src/test/java/io/reactivex/internal/operators/maybe/MaybeFromCallableTest.java
> +                return null;
Same

2016-10-09 17:48 UTC, JakeWharton commented on src/test/java/io/reactivex/internal/operators/maybe/MaybeFromRunnableTest.java
> +
Same

2016-10-09 20:11 UTC, vanniktech commented on src/main/java/io/reactivex/Maybe.java
> +    public static <T> Maybe<T> fromCompletable(final Completable completable) {
Yeah I copied the signature from the method above and that one is using final. Not everything is consistent though. I'll change it though

2016-10-11 06:58 UTC, vanniktech commented
Anything missing here? I updated this PR on Sunday with the requested changes.

2016-10-11 07:28 UTC, akarnokd approved these changes

2016-10-11 07:29 UTC, merged