1.x: Add null check to Observable.switchIfEmpty
ReactiveX/RxJava pull request #4791
Opened 2016-10-31 21:29 UTC by ortex

#4762

2016-10-31 21:54 UTC, JakeWharton approved these changes
A test would be lovely

2016-10-31 22:45 UTC, akarnokd requested changes
Please add a unit test.

2016-11-01 13:47 UTC, ortex commented
@akarnokd need more tests?

2016-11-01 14:31 UTC, akarnokd approved these changes

2016-11-01 14:32 UTC, merged