2.x: Unify CompositeDisposable error messages
ReactiveX/RxJava pull request #4934
Opened 2016-12-21 09:38 UTC by vanniktech

Unifies the CompositeDisposable error messages and make them a bit more helpful. Just seeing `d is null` reads oddly

2016-12-21 09:43 UTC, akarnokd requested changes
I find only the last one in `delete()` reasonable.

2016-12-21 09:43 UTC, akarnokd commented on src/main/java/io/reactivex/disposables/CompositeDisposable.java
> +        ObjectHelper.requireNonNull(resources, "resources are null");
It refers to the `resources` parameter so "is" is adequate here.

2016-12-21 09:43 UTC, akarnokd commented on src/main/java/io/reactivex/disposables/CompositeDisposable.java
> +        ObjectHelper.requireNonNull(d, "Disposable is null");
This is inconsistent as it names the type and not the parameter.

2016-12-21 09:43 UTC, akarnokd commented on src/main/java/io/reactivex/disposables/CompositeDisposable.java
> +        ObjectHelper.requireNonNull(d, "Disposable is null");
It should read `d is null`.

2016-12-21 10:24 UTC, vanniktech commented on src/main/java/io/reactivex/disposables/CompositeDisposable.java
> +        ObjectHelper.requireNonNull(d, "Disposable is null");
Are you open to rename the parameter from `d` to `disposable` then?

2016-12-21 10:36 UTC, akarnokd commented on src/main/java/io/reactivex/disposables/CompositeDisposable.java
> +        ObjectHelper.requireNonNull(d, "Disposable is null");
We want to avoid that in case in some odd JVM language the parameter name change is a breaking change.

2016-12-21 11:00 UTC, vanniktech commented on src/main/java/io/reactivex/disposables/CompositeDisposable.java
> +        ObjectHelper.requireNonNull(d, "Disposable is null");
Alright but don't you think that the error message `Disposable is null` is better than `d is null` regardless of the parameter name?

2016-12-21 11:18 UTC, akarnokd commented on src/main/java/io/reactivex/disposables/CompositeDisposable.java
> +        ObjectHelper.requireNonNull(d, "Disposable is null");
`d is null` is totally fine with me.

2016-12-23 12:57 UTC, vanniktech commented
If I'm the only one who thinks that those error messages are better and worth the change, I'll leave the decision up to you david. So if you want, you can close it.

2016-12-23 13:01 UTC, closed without merging