2.x: assertNever(T value) / assertNever(Predicate<T> valuePredicate)
ReactiveX/RxJava pull request #4994
Opened 2017-01-14 12:10 UTC by sergiomarquesmoura

This pull request adds to any class extending ```BaseConsumerTest``` the ability to assert that a given value was not emitted by the observable it was subscribed to, either with ```assertNever(T value)```or ```assertNever(Predicate<T> valuePredicate)```

2017-01-14 12:31 UTC, vanniktech commented on src/test/java/io/reactivex/subscribers/TestSubscriberTest.java
> +    public void assertNeverAtNotMatchingValue() {
those tests should also be in TestObserverTest

2017-01-14 12:39 UTC, akarnokd requested changes

2017-01-14 12:39 UTC, akarnokd commented on src/main/java/io/reactivex/observers/BaseTestConsumer.java
> +    public final U assertNever(T value) {
Experimental

2017-01-14 12:39 UTC, akarnokd commented on src/main/java/io/reactivex/observers/BaseTestConsumer.java
> +    public final U assertNever(Predicate<T> valuePredicate) {
Experimental

2017-01-14 12:39 UTC, akarnokd commented on src/test/java/io/reactivex/subscribers/TestSubscriberTest.java
> +    public void assertNeverAtNotMatchingValue() {
You have to test when the methods throw becaue the forbidden item is there.

2017-01-16 12:15 UTC, sergiomarquesmoura commented on src/test/java/io/reactivex/subscribers/TestSubscriberTest.java
> +    public void assertNeverAtNotMatchingValue() {
@akarnokd look at ```assertNeverAtMatchingValue()``` and ```
assertNeverAtMatchingPredicate()```. Is that what you mean?

Added the tests to ```TestObserverTest``` too.

2017-01-16 12:15 UTC, sergiomarquesmoura commented on src/main/java/io/reactivex/observers/BaseTestConsumer.java
> +    public final U assertNever(T value) {
Added it

2017-01-16 12:15 UTC, sergiomarquesmoura commented on src/main/java/io/reactivex/observers/BaseTestConsumer.java
> +    public final U assertNever(Predicate<T> valuePredicate) {
Added it

2017-01-16 12:20 UTC, akarnokd approved these changes

2017-01-17 08:31 UTC, akarnokd requested changes

2017-01-17 08:31 UTC, akarnokd commented on src/main/java/io/reactivex/observers/BaseTestConsumer.java
> +    public final U assertNever(Predicate<T> valuePredicate) {
`Predicate<? super T>`

2017-01-17 08:31 UTC, akarnokd commented on src/main/java/io/reactivex/observers/BaseTestConsumer.java
> +     */
`@since 2.0.5 - experimental`

2017-01-17 08:31 UTC, akarnokd commented on src/main/java/io/reactivex/observers/BaseTestConsumer.java
> +     */
`@since 2.0.5 - experimental`

2017-01-17 13:31 UTC, sergiomarquesmoura commented on src/main/java/io/reactivex/observers/BaseTestConsumer.java
> +     */
Done

2017-01-17 13:32 UTC, sergiomarquesmoura commented on src/main/java/io/reactivex/observers/BaseTestConsumer.java
> +     */
Done

2017-01-17 13:32 UTC, sergiomarquesmoura commented on src/main/java/io/reactivex/observers/BaseTestConsumer.java
> +    public final U assertNever(Predicate<T> valuePredicate) {
Done

2017-01-17 13:35 UTC, akarnokd approved these changes

2017-01-17 13:47 UTC, merged