Add scheduler creation factories
ReactiveX/RxJava pull request #5002
Opened 2017-01-18 11:31 UTC by hzsweers

Resolves #4993

This is a pretty vanilla copy from RxJava 1's implementation. Note that I had to tune NewThread scheduler to not be a singleton to support this.

We had talked about borrowing from project reactor's APIs for different overloads, let me know if you think we should add more fine-grained controls through these.

2017-01-18 11:32 UTC, hzsweers commented
One other thing I'm worried about - is `Schedulers` the best place for this? RxJava 1 had them in its `RxJavaHooks` class. My concern is that having these alongside the normal `io()`/`computation()`/etc factories will make them look overly inviting for use and accidental abuse.

2017-01-18 11:42 UTC, akarnokd requested changes

2017-01-18 11:42 UTC, akarnokd commented on src/main/java/io/reactivex/internal/schedulers/IoScheduler.java
> +        NONE = new CachedWorkerPool(0, null, WORKER_THREAD_FACTORY);
Any particular reason why this was moved to the end?

2017-01-18 11:42 UTC, akarnokd commented on src/main/java/io/reactivex/internal/schedulers/SingleScheduler.java
> +        this.threadFactory = ObjectHelper.requireNonNull(threadFactory, "threadFactory was null");
Either this is unnecessary or you forgot to do this with the other new constructors.

2017-01-18 11:42 UTC, akarnokd commented on src/main/java/io/reactivex/schedulers/Schedulers.java
> +     */
please add `@since 2.0.5 - experimental` as well for every new method.

2017-01-18 11:42 UTC, akarnokd commented on src/main/java/io/reactivex/schedulers/Schedulers.java
> +    public static Scheduler newComputation() {
I'm not sure we'd want to allow non-parameterized instances to be created.

2017-01-18 11:42 UTC, akarnokd commented on src/main/java/io/reactivex/schedulers/Schedulers.java
> +        return new ComputationScheduler(ObjectHelper.requireNonNull(threadFactory, "threadFactory == null"));
The usual NPE message is `threadFactory is null`.

2017-01-18 11:45 UTC, hzsweers commented on src/main/java/io/reactivex/internal/schedulers/IoScheduler.java
> +        NONE = new CachedWorkerPool(0, null, WORKER_THREAD_FACTORY);
It requires WORKER_THREAD_FACTORY to be initialized now since it's a parameter

2017-01-18 11:46 UTC, hzsweers commented on src/main/java/io/reactivex/internal/schedulers/SingleScheduler.java
> +        this.threadFactory = ObjectHelper.requireNonNull(threadFactory, "threadFactory was null");
Oops, meant to remove it from all these constructors and just do it in the factory methods, accidentally missed this one

2017-01-18 11:47 UTC, hzsweers commented on src/main/java/io/reactivex/schedulers/Schedulers.java
> +     */
Will do

2017-01-18 11:47 UTC, hzsweers commented on src/main/java/io/reactivex/schedulers/Schedulers.java
> +        return new ComputationScheduler(ObjectHelper.requireNonNull(threadFactory, "threadFactory == null"));
Gotcha, will update

2017-01-18 11:48 UTC, hzsweers commented on src/main/java/io/reactivex/schedulers/Schedulers.java
> +    public static Scheduler newComputation() {
Could you expand on that a bit?

2017-01-18 11:48 UTC, akarnokd commented
> One other thing I'm worried about - is Schedulers the best place for this? RxJava 1 had them in its RxJavaHooks class. My concern is that having these alongside the normal io()/computation()/etc factories will make them look overly inviting for use and accidental abuse.

Another problem is that people will try to override the scheduler-init with these method calls for `RxJavaPlugins` but referencing `Schedulers` will init the default schedulers regardless.

Indeed, `RxJavaPlugins` sounds like a better place for the methods, but keep only the `ThreadFactory` variants.

2017-01-18 11:49 UTC, hzsweers commented
Heading to bed right now but will update the PR in the morning with requested changes. Also let me know if there's anywhere I should put tests, as I wasn't sure what the right place would be.

2017-01-18 11:50 UTC, hzsweers commented
> Indeed, RxJavaPlugins sounds like a better place for the methods, but keep only the ThreadFactory variants.

Sounds good to me, will do that in my updates tomorrow

2017-01-18 11:54 UTC, akarnokd commented
Yes, tests that verify the custom thread factory actually worked by checking a custom thread name for each case.

2017-01-19 07:56 UTC, hzsweers commented on src/main/java/io/reactivex/internal/schedulers/SingleScheduler.java
> +        this.threadFactory = ObjectHelper.requireNonNull(threadFactory, "threadFactory was null");
e5c4a9e

2017-01-19 07:56 UTC, hzsweers commented on src/main/java/io/reactivex/schedulers/Schedulers.java
> +     */
262f669

2017-01-19 07:57 UTC, hzsweers commented on src/main/java/io/reactivex/schedulers/Schedulers.java
> +        return new ComputationScheduler(ObjectHelper.requireNonNull(threadFactory, "threadFactory == null"));
681b977

2017-01-19 07:59 UTC, hzsweers commented
> Indeed, RxJavaPlugins sounds like a better place for the methods

8b4d461

> but keep only the ThreadFactory variants.

8009333

Also tweaked the naming a bit. `newNewThread` was a little weird (went with `create`), and added `Scheduler` since we're not in the `Schedulers` class anymore.

> Yes, tests that verify the custom thread factory actually worked by checking a custom thread name for each case.

I tried setting this up matching some of the cdl-based approaches in the plugin tests but wan't able to get it working (just hangs). Pushed what I had in a1029b4, any insight?

2017-01-21 21:17 UTC, hzsweers commented
Heading on vacation for a couple weeks, but let me know what you think of getting the tests to work. I should have some time here and there to update the PR

2017-01-21 21:27 UTC, akarnokd commented
I've already told you: use the runnable in the factory method on the Thread constructor.

2017-01-24 17:11 UTC, hzsweers commented
> use the runnable in the factory method on the Thread constructor.

Aren't I just testing the test ThreadFactory implementations then, and not that the schedulers are hooked up properly to power the scheduler?

2017-01-24 17:14 UTC, akarnokd commented
https://docs.oracle.com/javase/8/docs/api/java/lang/Thread.html

https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/schedulers/RxThreadFactory.java#L66

2017-01-24 19:21 UTC, JakeWharton approved these changes

2017-01-24 19:21 UTC, JakeWharton commented on src/test/java/io/reactivex/plugins/RxJavaPluginsTest.java
> +            try {
remove double try

2017-01-24 19:21 UTC, JakeWharton commented on src/test/java/io/reactivex/plugins/RxJavaPluginsTest.java
> +                final AtomicReference<Thread> value = new AtomicReference<>();
Maybe change to `AtomicBoolean` and just run the predicate inside the worker?

2017-01-24 19:21 UTC, JakeWharton commented on src/test/java/io/reactivex/plugins/RxJavaPluginsTest.java
> +                final AtomicReference<Thread> value = new AtomicReference<>();
Then you don't even need to supply the `Thread` to the `Predicate` actually. It can verify whatever it wants.

2017-01-24 19:21 UTC, JakeWharton commented
What's the problem with the tests? They seem to be verifying that the supplied factory was used.

2017-01-24 19:22 UTC, JakeWharton commented
Oh you didn't pass the supplied `Runnable` when calling `new Thread()` inside the factory.

2017-01-25 02:32 UTC, hzsweers commented
> Oh you didn't pass the supplied Runnable when calling new Thread() inside the factory.

Ah! This is what I was missing, thanks for pointing that out. I've updated tests (which should now all be passing), and also made them a bit more robust (full integration with schedulers) to simulate a more real world use case.

2017-01-25 02:32 UTC, hzsweers commented on src/test/java/io/reactivex/plugins/RxJavaPluginsTest.java
> +            try {
90ae664

2017-01-25 02:42 UTC, hzsweers commented
Failing test looks like a flake...

2017-01-25 02:48 UTC, hzsweers commented
Wait no it's not. Repro'd locally, will fix

2017-01-25 06:16 UTC, hzsweers commented
Fixed, I think. I added manual shutdowns of schedulers after they're done. Only IO had this lifecycle issue over tests, but I did the shutdown in all to be safe.

2017-01-25 06:31 UTC, hzsweers commented
Ok this time it seems actually flaky, as the same commit passed in a different travis job against my fork - https://travis-ci.org/hzsweers/RxJava/builds/195074173

2017-01-25 08:07 UTC, akarnokd approved these changes

2017-01-25 08:07 UTC, akarnokd commented on src/main/java/io/reactivex/schedulers/Schedulers.java
> +     * Create an instance of the default {@link Scheduler} used for {@link Schedulers#computation()}
These need some rewording emphasizing that the there is always a new Scheduler instance, unlike with the non-new method call.

2017-01-25 08:07 UTC, akarnokd commented on src/main/java/io/reactivex/internal/schedulers/IoScheduler.java
> +        NONE = new CachedWorkerPool(0, null, WORKER_THREAD_FACTORY);
Right.

2017-01-25 08:07 UTC, akarnokd commented on src/main/java/io/reactivex/schedulers/Schedulers.java
> +    public static Scheduler newComputation() {
What is the use case for creating yet another computation/io/newThread scheduler with the default settings? I thought you wanted to override the `ThreadFactory`.

2017-01-25 08:07 UTC, akarnokd commented on src/test/java/io/reactivex/plugins/RxJavaPluginsTest.java
> +                return new Thread("Test");
I think this doesn't allow executing tasks because you ignore `r`.

2017-01-25 08:07 UTC, akarnokd commented on src/test/java/io/reactivex/plugins/RxJavaPluginsTest.java
> +    }
You have to shut down the scheduler (in a finally block) to avoid leaking threads.

2017-01-25 08:07 UTC, akarnokd commented on src/main/java/io/reactivex/plugins/RxJavaPlugins.java
> +     * @param threadFactory thread factory to use for creating worker threads. Note that this takes precedence over any
Please add notes to all of these methods something like this:

> Note that the returned `Scheduler` must be shut down manually if the `ThreadFactory` doesn't  create a daemon thread, otherwise the JVM may not quit.

2017-01-25 08:07 UTC, akarnokd commented on src/main/java/io/reactivex/plugins/RxJavaPlugins.java
> +     * @param threadFactory thread factory to use for creating worker threads. Note that this takes precedence over any
The "Note that this takes precedence..." may be misleading. The number of threads is still based on the system configuration. I'd remove this sentence entirely

2017-01-25 08:22 UTC, merged

2017-01-25 08:23 UTC, hzsweers commented
Thanks!