Feature/#4876 nonnull annotations
ReactiveX/RxJava pull request #5051
Opened 2017-02-02 20:14 UTC by jschneider

Starting to add @NonNull and @Nullable annotations.

I decided to add a compileOnly dependency to findbugs:jsr305 artifact.

We could also use "io.reactivex.annotations.NonNull" which already exists. But there is no "io.reactivex.annotations.Nullable" annotation which is at least as important in my experience.

Since this are only annotations, it is no problem when the class files are missing at compile time (JLS 9.6.1.2 Retention).

I have started to add annotations in the Scheduler and RxJavaPlugins.
The test RxJavaPlugins contains some invalid checks using null (lines 1353 and following).

This pull request is work in progress and should be discussed.

Questions so far:
- use jsr305 (compileOnly) or existing annotation in io.reactivex?
- (if not using jsr305): Use own @Nullable annotation or try to get one added to "io.reactivex"? Or skip these completely (which misses the point of the static code analysis)
- Why has there been tests calling the RxJavaPlugins.on*Scheduler with null arguments? Can these be removed securely?

2017-02-02 20:14 UTC, jschneider commented
Related issue: #4876

2017-02-02 20:49 UTC, akarnokd commented
Maybe it wasn't well articulated, but based on #5023 I thought we try with just the functional interfaces and come back later if it was not enough.

> I decided to add a compileOnly dependency to findbugs:jsr305 artifact.

We rather use our own annotations as most tools allow customizing what annotations to consider.

Expect futher comments inline.

2017-02-02 21:03 UTC, akarnokd requested changes
All annotations should be RxJava's own.

2017-02-02 21:03 UTC, akarnokd commented on src/main/java/io/reactivex/Scheduler.java
> +    public Disposable scheduleDirect(@Nonnull Runnable run, long delay, TimeUnit unit) {
`TimeUnit`s should also receive our own non-null annotation.

2017-02-02 21:03 UTC, akarnokd commented on src/main/java/io/reactivex/plugins/RxJavaPlugins.java
> -
Please don't remove these empty lines.

2017-02-02 21:03 UTC, akarnokd commented on src/main/java/io/reactivex/plugins/RxJavaPlugins.java
> +      @Nullable BiFunction<Completable, CompletableObserver, CompletableObserver> onCompletableSubscribe) {
Indentation

2017-02-02 21:03 UTC, akarnokd commented on src/main/java/io/reactivex/plugins/RxJavaPlugins.java
> +      @Nullable BiFunction<Observable, Observer, Observer> onObservableSubscribe) {
Please adjust indentation.

2017-02-02 21:03 UTC, akarnokd commented on src/test/java/io/reactivex/internal/operators/flowable/FlowableReplayTest.java
> +        @javax.annotation.Nonnull
I don't think it is worth updating the unit tests.

2017-02-02 21:03 UTC, akarnokd commented on src/test/java/io/reactivex/plugins/RxJavaPluginsTest.java
> +                assertNull(RxJavaPlugins.onComputationScheduler(null));
Instead of "disabling" this, change it to use the thin scheduler below and `assertSame` instead of null.

2017-02-03 07:20 UTC, jschneider commented
Thanks for the feedback. I will improve the pull request further.

2017-02-03 09:06 UTC, akarnokd approved these changes

2017-02-03 09:06 UTC, akarnokd commented on src/main/java/io/reactivex/annotations/Nullable.java
> +@Documented
Could you add a short javadoc to this and `@NonNull` while you are at it?

2017-02-03 09:56 UTC, jschneider commented on src/main/java/io/reactivex/Scheduler.java
> +    public Disposable scheduleDirect(@Nonnull Runnable run, long delay, TimeUnit unit) {
done

2017-02-03 10:08 UTC, jschneider commented on src/main/java/io/reactivex/plugins/RxJavaPlugins.java
> -
done

2017-02-03 10:11 UTC, jschneider commented on src/main/java/io/reactivex/plugins/RxJavaPlugins.java
> +      @Nullable BiFunction<Completable, CompletableObserver, CompletableObserver> onCompletableSubscribe) {
done

2017-02-03 10:11 UTC, jschneider commented on src/main/java/io/reactivex/plugins/RxJavaPlugins.java
> +      @Nullable BiFunction<Observable, Observer, Observer> onObservableSubscribe) {
done

2017-02-03 10:11 UTC, jschneider commented on src/test/java/io/reactivex/internal/operators/flowable/FlowableReplayTest.java
> +        @javax.annotation.Nonnull
Idea did it on itself ;-)
If it is ok, I'd just leave it.

2017-02-03 10:12 UTC, jschneider commented on src/test/java/io/reactivex/plugins/RxJavaPluginsTest.java
> +                assertNull(RxJavaPlugins.onComputationScheduler(null));
I removed the null checks completely. As you said, below are the assertSame checks. This should be good enough.

2017-02-03 10:29 UTC, merged