Feature/#5045 more generics in RxJavaPlugins
ReactiveX/RxJava pull request #5058
Opened 2017-02-03 14:47 UTC by jschneider

I widened the bounds for the functions. Looks good for me.
Related to #5045

2017-02-03 15:09 UTC, akarnokd requested changes

2017-02-03 15:09 UTC, akarnokd commented on src/test/java/io/reactivex/plugins/RxJavaPluginsTest.java
> +import io.reactivex.Completable;
Please keep imports as *

2017-02-03 16:44 UTC, akarnokd commented
Looks like this needs rebasing. I'm sorrry, I'm trying to merge your PRs in proper order but multiple recent PRs change the same file(s).

2017-02-03 20:44 UTC, jschneider commented
Yeah, no problem. Rebasing isn't too difficult ;-)

2017-02-05 19:00 UTC, jschneider commented on src/test/java/io/reactivex/plugins/RxJavaPluginsTest.java
> +import io.reactivex.Completable;
Yes. Changed the code style settings accordingly.
Do you have a code style configuration for IntelliJ Idea?

2017-02-05 19:00 UTC, jschneider commented
fixed import and rebased

2017-02-05 19:08 UTC, akarnokd commented
Looks like there is a [compilation error](https://travis-ci.org/ReactiveX/RxJava/builds/198621003#L190) with the changes.

2017-02-05 19:40 UTC, jschneider commented
Uups. Fixed it (at least I hope)

2017-02-06 19:26 UTC, akarnokd approved these changes

2017-02-06 19:26 UTC, akarnokd commented on src/test/java/io/reactivex/plugins/RxJavaPluginsTest.java
> +import io.reactivex.disposables.Disposable;
Could you also restore these import changes to their * form?

2017-02-06 19:26 UTC, akarnokd commented on src/test/java/io/reactivex/plugins/RxJavaPluginsTest.java
> +import io.reactivex.functions.BiFunction;
Please restore these as well.

2017-02-06 19:26 UTC, merged