When declaring Functions/BiFunctions as parameter, ? super / ? extends is used
ReactiveX/RxJava pull request #5059
Opened 2017-02-03 15:02 UTC by jschneider

I think a function should never be declared without "super/extends" as method parameter.
I have found a few instances where this has been the case.

In the most common cases this shouldn't make a difference, but sometimes it helps a lot...

2017-02-03 16:47 UTC, akarnokd commented
This also needs rebasing. In addition, please check locally that:

  - if you manually change the compiler settings to Java 8 in your IDE, there is no compilation error
  - if you temporarily change the build.gradle to target java 8 and there is no compilation error when building.

2017-02-04 19:39 UTC, davidmoten commented on src/main/java/io/reactivex/Flowable.java
> +    public final Maybe<T> reduce(BiFunction<? super T, ? super  T, ? extends T> reducer) {
This sort of change is a good idea for me but problem is that it is probably a breaking change in that user source that used to compile may no longer compile:

This 
```java
Maybe<Integer> result = flowable.reduce(f);
```
will need to be
```java
Maybe<Integer> result = flowable.<Integer>reduce(f);
```

I haven't checked this yet, can you confirm?

I can live with it. @akarnokd?

2017-02-04 19:43 UTC, akarnokd commented on src/main/java/io/reactivex/Flowable.java
> +    public final Maybe<T> reduce(BiFunction<? super T, ? super  T, ? extends T> reducer) {
`reduce(T, T, T)` was discussed quite a while back and it has to stay non-variant. One of the reasons is the limits of javac and what @davidmoten showed.

2017-02-04 19:49 UTC, akarnokd requested changes

2017-02-04 19:49 UTC, akarnokd commented on src/main/java/io/reactivex/Flowable.java
> +    public final Flowable<T> scan(BiFunction<? super T, ? super T, ? extends T> accumulator) {
No good, same situation as with `reduce(T, T, T)`.

2017-02-04 19:49 UTC, akarnokd commented on src/main/java/io/reactivex/Flowable.java
> +        Function<? super T, ? extends T> valueSelector = Functions.identity();
Such changes in our own source is a good indication there will be generics issues for the users of the library.

2017-02-04 19:49 UTC, akarnokd commented on src/test/java/io/reactivex/plugins/RxJavaPluginsTest.java
> +import io.reactivex.Completable;
Please don't unroll * imports

2017-02-04 19:49 UTC, akarnokd commented on src/main/java/io/reactivex/plugins/RxJavaPlugins.java
> +    static volatile Function<? super Runnable, ? extends Runnable> onScheduleHandler;
I'm not too keen on these variance changes unless you can show that there is an inference problem with lambdas under 8 without them.

2017-02-05 19:02 UTC, jschneider commented
Ok. So I unterstand that we leave the source code as it is.
Will close the pull request. Thanks for the feedback.

2017-02-05 19:02 UTC, closed without merging

2017-02-05 19:28 UTC, jschneider commented on src/main/java/io/reactivex/Flowable.java
> +    public final Maybe<T> reduce(BiFunction<? super T, ? super  T, ? extends T> reducer) {
I don't want to keep pushing a finished topic. But just for your interest: This code compiles (have tried with 1.6 and 1.8):

I have added this test case to this pull request, if anybody wants to take a look.

````
@Test
    public void basics() throws Exception {
        Flowable<Integer> flowable = Flowable.just(1, 2, 3, 4);

        BiFunction<Integer, Integer, Integer> sumReducer = new BiFunction<Integer, Integer, Integer>() {
            @Override
            public Integer apply(Integer integer, Integer integer2) throws Exception {
                return integer + integer2;
            }
        };

        Maybe<Integer> reduced = flowable.reduce(sumReducer);

        reduced.subscribe(new Consumer<Integer>() {
            @Override
            public void accept(Integer integer) throws Exception {
                assertEquals(10, integer, 0);
            }
        });
    }

    @Test
    public void reduceWithSuperType() throws Exception {
        Flowable<Integer> flowable = Flowable.just(1, 2, 3, 4);

        BiFunction<Number, Number, Integer> sumReducer = new BiFunction<Number, Number, Integer>() {
            @Override
            public Integer apply(Number integer, Number integer2) throws Exception {
                int value = integer.intValue() + integer2.intValue();
                return value;
            }
        };

        Maybe<Integer> reduced = flowable.reduce(sumReducer);
        reduced.subscribe(new Consumer<Integer>() {
            @Override
            public void accept(Integer integer) throws Exception {
                assertEquals(10, integer, 0);
            }
        });
    }

    @Test
    public void reduceWithSuperTypeNumberFlowable() throws Exception {
        Flowable<Number> flowable = Flowable.<Number>just(1, 2, 3, 4);

        BiFunction<Number, Number, Integer> sumReducer = new BiFunction<Number, Number, Integer>() {
            @Override
            public Integer apply(Number integer, Number integer2) throws Exception {
                int value = integer.intValue() + integer2.intValue();
                return value;
            }
        };

        Maybe<Number> reduced = flowable.reduce(sumReducer);
        reduced.subscribe(new Consumer<Number>() {
            @Override
            public void accept(Number integer) throws Exception {
                assertEquals(10, integer.doubleValue(), 0);
            }
        });
    }

    @Test
    public void reduceWithSuperTypeNumberFlowable2() throws Exception {
        Flowable<Number> flowable = Flowable.<Number>just(1, 2, 3, 4);

        BiFunction<Number, Number, Number> sumReducer = new BiFunction<Number, Number, Number>() {
            @Override
            public Number apply(Number integer, Number integer2) throws Exception {
                int value = integer.intValue() + integer2.intValue();
                return value;
            }
        };

        Maybe<Number> reduced = flowable.reduce(sumReducer);
        reduced.subscribe(new Consumer<Number>() {
            @Override
            public void accept(Number integer) throws Exception {
                assertEquals(10, integer.doubleValue(), 0);
            }
        });
    }