1.x fix async single error report (bug #5237)
ReactiveX/RxJava pull request #5241
Opened 2017-03-27 21:38 UTC by passsy

Targets issue #5237 where an `Exception` in `onSuccess` of an async `Single` wasn't forwarded to `onError`. For a sync `Single` it already gets forwarded correctly.

Example:
```java
Single.just("test")
        .delay(1, TimeUnit.MILLISECONDS)
        .subscribe(
        result -> {
            System.out.println("got text: " + result);
            throw new IllegalStateException("single async something is wrong");
            // onError will not be called, hard crash
        },
        e -> {
            // not called
            System.out.println("caught error " + e.getMessage());
            e.printStackTrace();
        });
```

I introduced `SafeSingleSubscriber` analog to `SafeSubscriber` of `Observable`. It makes sure `onError` gets called when `onSuccess` throws.

I had to introduce `private Subscription unsafeSubscribe(SingleSubscriber)` for internal usage of `Single#subscribeOn()` and `Single#unsubscribeOn()` which should *not* be wrapped by `SafeSingleSubscriber`.

Furthermore I added the `subscriber.isUnsubscribed()` case in all three `subscribe` methods analog to `Observable#subscribe`
```java
    // ...
    if (subscriber.isUnsubscribed()) {
        RxJavaHooks.onError(RxJavaHooks.onSingleError(e));
    } else {
        // try forwarding error to subscriber
    }
    // ....
```
as well as `Single#subscribe` now throws `OnErrorFailedException` instead of `RuntimeException` when calling `subscriber.onError(e)` fails.

2017-03-27 23:21 UTC, akarnokd requested changes
I'm sorry, the changes to Single are unacceptable. You could have added a `safeSubscribe()` method without breaking anyone.

2017-03-27 23:21 UTC, akarnokd commented on src/main/java/rx/Single.java
> +    public final Subscription subscribe(SingleSubscriber<? super T> subscriber) {
There were concerns that some languages do require the parameter names to remain the same, so no public renamings.

2017-03-27 23:21 UTC, akarnokd commented on src/main/java/rx/Single.java
> +        if (!(subscriber instanceof SafeSingleSubscriber)) {
This undoes a lot of the perf optimizations. Especially without a matching accessible `unsafeSubscribe`.

2017-03-27 23:21 UTC, akarnokd commented on src/main/java/rx/observers/SafeSingleSubscriber.java
> +            Exceptions.throwOrReport(e, this);
The `Single` protocol is `onSuccess | onError`. You can't call `onError` when `onSuccess` has been called.

2017-03-27 23:21 UTC, akarnokd commented on src/test/java/rx/internal/operators/SingleFromEmitterTest.java
> +        final AtomicInteger onErrorCallsCounter = new AtomicInteger();
Changing existing unit test is a sign of behavior change that may be incompatible with existing uses.

2017-03-27 23:29 UTC, passsy commented
What can I say, tests are working on my maschine 😅 Is it normal that rx1 tests are flaky?

```
pascalwelsch$ ./gradlew test
...
BUILD SUCCESSFUL

Total time: 3 mins 54.445 secs
```

2017-03-28 00:11 UTC, passsy commented
I tried to revert to the behaviour in `1.1.9`. I have some problems upgrading because of this behaviour change of not calling `onError` introduced in `1.2.2`. Especially frustrating because this is the behaviour for synchronous Singles but changes when adding a `delay`.

What about those `Single.using` tests? They are now working correctly as far as I understand. Is the change of those assertions intended?

I'll try to change the PR without changing the current behaviour.

2017-03-28 00:12 UTC, passsy commented on src/test/java/rx/internal/operators/SingleFromEmitterTest.java
> +        final AtomicInteger onErrorCallsCounter = new AtomicInteger();
I intentional changed the behaviour here

2017-03-28 00:13 UTC, passsy commented on src/main/java/rx/observers/SafeSingleSubscriber.java
> +            Exceptions.throwOrReport(e, this);
Aye

2017-03-28 08:25 UTC, akarnokd commented
> I tried to revert to the behaviour in 1.1.9. I have some problems upgrading because of this behaviour change of not calling onError introduced in 1.2.2.

Where do you have this problem? You could have just delegated to your error handler:

```java
Action1<Throwabe> onErrorHandler = ...

Action1<T> onSuccessHandler = value -> {
    try {
          doSomething(value);
    } catch (Throwable ex) {
          onErrorHandler.call(ex);
    }
};

source.subscribe(onSuccessHandler, onErrorHandler);
```

> What about those Single.using tests? They are now working correctly as far as I understand. Is the change of those assertions intended?

The current (unsafe)subscribe doesn't call unsubscribe. The rest of the test is still valuable.

2017-03-28 08:26 UTC, akarnokd commented
> I'll try to change the PR without changing the current behaviour.

It's much cleaner if you start over.

2017-04-06 13:21 UTC, passsy commented
Was building in the complete wrong direction
~close

2017-04-06 13:21 UTC, closed without merging