Remove CheckReturnValue on methods returning Disposable
ReactiveX/RxJava pull request #5244
Opened 2017-03-30 15:03 UTC by markelliot

Per #4878.

2017-03-31 09:50 UTC, akarnokd reviewed
Because it works for me either way, as I don't use tools that require `CheckReturnValue`, I defer to the judgement of @JakeWharton and @vanniktech on this.

2017-03-31 09:50 UTC, akarnokd commented on src/test/java/io/reactivex/BaseTypeAnnotations.java
> +                if (m.getReturnType().equals(Disposable.class)) {
Looks like this needs to import `io.reactivex.disposables.Disposable`. Did you post this from IntelliJ?

2017-03-31 10:10 UTC, vanniktech requested changes
I'm against this change. In the vast majority of the cases that this was triggered, I actually forgot to handle the Disposable and this annotation saved me.

2017-03-31 10:31 UTC, markelliot commented
Cool, for consistency, then, should the other Disposable returning subscribe method also pick up this annotation?

2017-03-31 10:31 UTC, closed without merging

2017-03-31 11:07 UTC, vanniktech commented
David was against this one. Also like Jake said it's an antipattern and shouldn't be used in applications.

2017-03-31 11:15 UTC, akarnokd commented
To sum up, the arg-less `subscribe()` is for testing only and I don't think it should be in production flows. Therefore, a `CheckReturnValue` may be distracting on them. For all the other overloads, the dominant use is with `CompositeDisposable.add()` for flows started by the activity and have to be stopped hence the return value should be taken care of.

2017-12-11 02:02 UTC, btilbrook-nextfaze commented
Since when did the dominant use case dictate that all other use cases have to suppress a warning? I thought RxJava was a general-purpose lib.

Assigning the `Disposable` to a var doesn't even mean you're disposing it correctly, or at all. I don't think that can be determined by static analysis.

`@CheckReturnValue`'s use here is an excessively opinionated decision that damages user code, by forcing warning suppression (and adding unwanted noise) when the code otherwise handles the `Disposable` effectively using another technique such as RxLifecycle or `takeUntil`.

The annotation is better suited to scenarios where failing to handle the result is _guaranteed_ to be bad or pointless, like creating a copy of an immutable collection using its `add(elements)` method.

2017-12-11 02:17 UTC, JakeWharton commented
Strongly disagree. The absence of the annotation creates bugs. Its presence
requires suppression when you're doing non-standard management that itself
doesn't even guarantee correctness which sounds perfectly reasonable.

On Sun, Dec 10, 2017, 9:02 PM btilbrook-nextfaze <notifications@github.com>
wrote:

> Since when did the dominant use case dictate that all other use cases have
> to suppress a warning? I thought RxJava was a general-purpose lib.
>
> Assigning the Disposable to a var doesn't even mean you're disposing it
> correctly, or at all. I don't think that can be determined by static
> analysis.
>
> @CheckReturnValue's use here is an excessively opinionated decision that
> damages user code, by forcing warning suppression (and adding unwanted
> noise) when the code otherwise handles the Disposable effectively using
> another technique such as RxLifecycle or takeUntil.
>
> The annotation is better suited to scenarios where failing to handle the
> result is *guaranteed* to be bad or pointless, like creating a copy of an
> immutable collection using its add(elements) method.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/ReactiveX/RxJava/pull/5244#issuecomment-350604373>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAEEEWWGGyoshnwzgQbEMkRG-yXz16a6ks5s_I1LgaJpZM4Muff_>
> .
>

2017-12-11 03:01 UTC, btilbrook-nextfaze commented
I feel its use here dilutes the value of the annotation, and is in a sense, a stamp of disapproval for RxLifecycle and equivalent solutions.

2017-12-11 08:43 UTC, akarnokd commented
You can always implement `Subscriber`/`Observer` and the `subscribe()` for them doesn't return `Disposable`.

2017-12-11 23:23 UTC, btilbrook-nextfaze commented
I'd be interested to hear your opinions on RxLifecycle & co, since this decision punishes their use.

2017-12-11 23:35 UTC, akarnokd commented
Try [AutoDispose](https://github.com/uber/AutoDispose) instead.

2017-12-11 23:52 UTC, btilbrook-nextfaze commented
Thanks. Looked into this briefly a while back but didn't see a lot of value in migrating to it. Will give it more consideration now.