More nullability annotations
ReactiveX/RxJava pull request #5251
Opened 2017-03-31 16:33 UTC by mibac138

Added nullability annotations to:
- Disposables
- Observers
and some others

2017-03-31 16:36 UTC, vanniktech requested changes
You probably don't want to mess up the imports.

2017-03-31 17:02 UTC, mibac138 commented
@vanniktech is it okay now?

2017-03-31 17:12 UTC, akarnokd requested changes
Some of the non-public components don't need annotation.

2017-03-31 17:12 UTC, akarnokd commented on src/main/java/io/reactivex/Single.java
> +import io.reactivex.internal.functions.Functions;
Please don't unroll star imports.

2017-03-31 17:12 UTC, akarnokd commented on src/main/java/io/reactivex/disposables/ActionDisposable.java
> +    ActionDisposable(@NonNull Action value) {
Non-public components don't really need such annotations.

2017-03-31 17:12 UTC, akarnokd commented on src/main/java/io/reactivex/disposables/CompositeDisposable.java
> +import io.reactivex.annotations.NonNull;
Please don't unroll star imports.

2017-03-31 17:12 UTC, akarnokd commented on src/main/java/io/reactivex/disposables/Disposables.java
> +import io.reactivex.internal.functions.Functions;
Please don't unroll star imports.

2017-03-31 17:12 UTC, akarnokd commented on src/main/java/io/reactivex/disposables/FutureDisposable.java
> +    FutureDisposable(@Nullable Future<?> run, boolean allowInterrupt) {
Non-public components don't really need this annotation.

2017-03-31 17:12 UTC, akarnokd commented on src/main/java/io/reactivex/disposables/ReferenceDisposable.java
> +    ReferenceDisposable(@NonNull T value) {
Non-public components don't need this annotation.

2017-03-31 17:12 UTC, akarnokd commented on src/main/java/io/reactivex/disposables/RunnableDisposable.java
> +    RunnableDisposable(@NonNull Runnable value) {
Non-public...

2017-03-31 17:12 UTC, akarnokd commented on src/main/java/io/reactivex/disposables/SubscriptionDisposable.java
> +    SubscriptionDisposable(@NonNull Subscription value) {
Non-public...

2017-03-31 17:12 UTC, akarnokd commented on src/main/java/io/reactivex/flowables/ConnectableFlowable.java
>      public Flowable<T> autoConnect(int numberOfSubscribers, Consumer<? super Disposable> connection) {
NonNull could be added to the `connection` parameter as well as to `connect(Consumer)`.

2017-03-31 17:12 UTC, akarnokd commented on src/main/java/io/reactivex/internal/disposables/DisposableHelper.java
> +    public static boolean isDisposed(@Nullable Disposable d) {
For anything below `internal.*` I don't think annotations are necessary.

2017-03-31 17:12 UTC, akarnokd commented on src/main/java/io/reactivex/observables/ConnectableObservable.java
>      public Observable<T> autoConnect(int numberOfSubscribers, Consumer<? super Disposable> connection) {
Non-null consumer and `connect(Consumer)` also needs annotation.

2017-03-31 17:12 UTC, akarnokd commented on src/main/java/io/reactivex/observers/DisposableCompletableObserver.java
> +    @NonNull
I'm not sure non-public fields actually need such annotations.

2017-03-31 17:12 UTC, akarnokd commented on src/main/java/io/reactivex/observers/ResourceSingleObserver.java
> +    @NonNull
Unnecessary.

2017-03-31 17:12 UTC, akarnokd commented on src/main/java/io/reactivex/observers/SafeObserver.java
> +import io.reactivex.annotations.NonNull;
Please don't unroll star imports.

2017-03-31 17:12 UTC, akarnokd commented on src/main/java/io/reactivex/observers/SafeObserver.java
> +    @Nullable
No need for it on non-public fields.

2017-03-31 17:12 UTC, akarnokd commented on src/main/java/io/reactivex/parallel/ParallelFlowable.java
> +import io.reactivex.Flowable;
Please don't unroll star imports.

2017-03-31 17:12 UTC, akarnokd commented on src/main/java/io/reactivex/processors/AsyncProcessor.java
> +import io.reactivex.annotations.*;
What IDE are you using that reorders imports?

2017-03-31 17:12 UTC, akarnokd commented on src/main/java/io/reactivex/processors/AsyncProcessor.java
> +    @NonNull
Non-public, not necessary.

2017-03-31 17:12 UTC, akarnokd commented on src/main/java/io/reactivex/schedulers/Timed.java
> +    @Nullable
Not necessary.

2017-03-31 17:12 UTC, akarnokd commented on src/main/java/io/reactivex/schedulers/Timed.java
> +    public Timed(@Nullable T value, long time, @NonNull TimeUnit unit) {
Why is this nullable?

2017-04-01 16:49 UTC, mibac138 commented on src/main/java/io/reactivex/processors/AsyncProcessor.java
> +import io.reactivex.annotations.*;
IntelliJ IDEA

2017-04-01 17:59 UTC, akarnokd reviewed
A couple of changes are still needed.

2017-04-01 17:59 UTC, akarnokd commented on src/main/java/io/reactivex/exceptions/CompositeException.java
> +    public CompositeException(@Nullable Throwable... exceptions) {
This should be `@NonNull`.

2017-04-01 17:59 UTC, akarnokd commented on src/main/java/io/reactivex/exceptions/CompositeException.java
> +    public CompositeException(@Nullable Iterable<? extends Throwable> errors) {
This should be `@NonNull`.

2017-04-01 17:59 UTC, akarnokd commented on src/main/java/io/reactivex/exceptions/Exceptions.java
> +    public static RuntimeException propagate(@Nullable Throwable t) {
The argument should be `@NonNull`.

2017-04-01 17:59 UTC, akarnokd commented on src/main/java/io/reactivex/exceptions/Exceptions.java
> +    public static void throwIfFatal(@Nullable Throwable t) {
The argument should be `@NonNull`.

2017-04-01 17:59 UTC, akarnokd commented on src/main/java/io/reactivex/exceptions/OnErrorNotImplementedException.java
> +    public OnErrorNotImplementedException(String message, @Nullable Throwable e) {
The `e` argument should be `@NonNull`.

2017-04-01 17:59 UTC, akarnokd commented on src/main/java/io/reactivex/exceptions/OnErrorNotImplementedException.java
> +    public OnErrorNotImplementedException(@Nullable Throwable e) {
The argument should be non-null. It's just a safeguard to make sure a null is recorded as NPE.

2017-04-01 17:59 UTC, akarnokd commented on src/main/java/io/reactivex/flowables/GroupedFlowable.java
> +    @Nullable
Nullable annotation on package-private fields are unnecessary.

2017-04-01 17:59 UTC, akarnokd commented on src/main/java/io/reactivex/internal/disposables/DisposableHelper.java
> +import java.util.concurrent.atomic.AtomicReference;
Please restore the original file if there is no actual (code) change.

2017-04-01 17:59 UTC, akarnokd commented on src/main/java/io/reactivex/observables/GroupedObservable.java
> +    @Nullable
No need to annotate this.

2017-04-01 17:59 UTC, akarnokd commented on src/main/java/io/reactivex/observers/SerializedObserver.java
> +
Whitespace added?

2017-04-01 17:59 UTC, akarnokd commented on src/main/java/io/reactivex/processors/AsyncProcessor.java
> +
Whitespace added?

2017-04-01 17:59 UTC, akarnokd commented on src/main/java/io/reactivex/schedulers/Timed.java
> +    @Nullable
This should be `@NonNull`.

2017-04-01 17:59 UTC, akarnokd commented on src/main/java/io/reactivex/subjects/SingleSubject.java
> +
Whitespace?

2017-04-01 19:11 UTC, akarnokd approved these changes

2017-04-01 19:11 UTC, merged

2017-04-21 10:11 UTC, PaulWoitaschek commented on src/main/java/io/reactivex/exceptions/OnErrorNotImplementedException.java
> +    public OnErrorNotImplementedException(String message, @NonNull Throwable e) {
Looks like this should be Nullable

2017-04-21 10:11 UTC, PaulWoitaschek commented on src/main/java/io/reactivex/exceptions/OnErrorNotImplementedException.java
> +    public OnErrorNotImplementedException(@NonNull Throwable e) {
Nullable too.

2017-04-21 10:11 UTC, PaulWoitaschek commented on src/main/java/io/reactivex/exceptions/CompositeException.java
> +    public CompositeException(@NonNull Throwable... exceptions) {
Nullable instead? The code handles it explicitly.