Adding Flowable.throttleAndSample - Conflate operator
ReactiveX/RxJava pull request #5968
Opened 2018-04-22 21:17 UTC by 0ximDigital

This pull request is to add Flowable.throttleAndSample operator as discussed in #4856

2018-04-22 21:36 UTC, akarnokd requested changes

2018-04-22 21:36 UTC, akarnokd commented on src/main/java/io/reactivex/Flowable.java
> +    @SchedulerSupport(SchedulerSupport.COMPUTATION)
These need version tag `@since 2.1.13 - experimental` and `@Experimental` annotation.

2018-04-22 21:36 UTC, akarnokd commented on src/main/java/io/reactivex/internal/operators/flowable/FlowableThrottleAndSample.java
> +    private final long windowDuration;
Please no `private` components.

2018-04-22 21:36 UTC, akarnokd commented on src/test/java/io/reactivex/internal/operators/flowable/FlowableThrottleAndSampleTest.java
> +package io.reactivex.internal.operators.flowable;
Please add the standard file header.

2018-04-22 21:36 UTC, akarnokd commented on src/main/java/io/reactivex/internal/operators/flowable/FlowableThrottleAndSample.java
> +package io.reactivex.internal.operators.flowable;
Please add the standard file header.

2018-04-22 21:36 UTC, akarnokd commented on src/main/java/io/reactivex/internal/operators/flowable/FlowableThrottleAndSample.java
> +            throttling.dispose();
There is a race here. If `run()` gets here and `onNext` is fired, throttling will be disposed and the `onNext` value gets emitted. Here then the cached value gets emitted as well and now there are two tasks delayed for the subsequent interactions.

2018-04-22 21:36 UTC, akarnokd commented on src/main/java/io/reactivex/internal/operators/flowable/FlowableThrottleAndSample.java
> +            actual.onComplete();
This could race with the emission of `run()`.

2018-04-22 21:37 UTC, akarnokd submitted a review, later dismissed

2018-04-22 21:37 UTC, akarnokd commented on src/main/java/io/reactivex/Flowable.java
> +     * <dt><b>Scheduler:</b></dt>
Backpressure definition is required.

2018-04-22 21:37 UTC, akarnokd commented on src/main/java/io/reactivex/Flowable.java
> +    @SchedulerSupport(SchedulerSupport.COMPUTATION)
Also `@BlackpressureSupport`.

2018-04-22 22:39 UTC, akarnokd commented on src/test/java/io/reactivex/flowable/FlowableNullTests.java
> +    @Test(expected = NullPointerException.class)
This is not necessary, null checks are done automatically in `ParamValidationCheckerTest`.

2018-04-22 22:41 UTC, akarnokd commented
Please run the unit tests in `io.reactivex` locally first to resolve the style validation issues so you don't have to wait 15 minutes for Travis CI.

2018-04-25 18:13 UTC, artem-zinnatullin commented on src/main/java/io/reactivex/Flowable.java
> +     * Returns a Flowable that emits an item immediately and then no frequently than specified duration,
supernit: duration → period or interval?

2018-04-25 18:13 UTC, artem-zinnatullin commented on src/main/java/io/reactivex/Flowable.java
> +     * Optionally emits the very last upstream item when the upstream completes.
Remove "very last" part from javadoc of this overload?

2018-04-25 18:13 UTC, artem-zinnatullin commented on src/main/java/io/reactivex/Flowable.java
> +     * Optionally emits the very last upstream item when the upstream completes.
And other similar overloads

2018-04-25 21:38 UTC, 0ximDigital commented on src/main/java/io/reactivex/Flowable.java
> +     * Returns a Flowable that emits an item immediately and then no frequently than specified duration,
Sounds good 👍

2018-04-26 08:43 UTC, akarnokd requested changes

2018-04-26 08:43 UTC, akarnokd commented on src/main/java/io/reactivex/internal/operators/flowable/FlowableThrottleAndSample.java
> +            DisposableHelper.dispose(timer);
Not really necessary, `worker.dispose()` will dispose any outstanding timer action.

2018-04-26 08:43 UTC, akarnokd commented on src/main/java/io/reactivex/internal/operators/flowable/FlowableThrottleAndSample.java
> +            actual.onComplete();
the `emitFromRun` may still be running at this point and you have concurrent `onNext`/`onComplete` invocation.

2018-04-26 08:43 UTC, akarnokd commented on src/main/java/io/reactivex/internal/operators/flowable/FlowableThrottleAndSample.java
> +                cancel();
`isDone` should be set here so that `onError`/`onComplete` doesn't get called again.

2018-04-26 08:43 UTC, akarnokd commented on src/main/java/io/reactivex/internal/operators/flowable/FlowableThrottleAndSample.java
> +            actual.onError(t);
Same problem as with `onComplete`, `emitFromRun` may be still going on.

2018-04-26 08:46 UTC, akarnokd commented
Since you have to take into account the concurrency of `emitFromRun` with the termination of the main source, you most likely can't avoid a queue-drain approach. The closest similar operator is the `onBackpressureLatest` except the drain is triggered by the `run()` and not `request`.

2018-04-26 08:59 UTC, akarnokd commented on src/main/java/io/reactivex/internal/operators/flowable/FlowableThrottleAndSample.java
> +    abstract static class ThrottleAndSampleSubscriber<T> extends AtomicReference<T> implements FlowableSubscriber<T>, Subscription, Runnable {
Accessing `timerInProgress` happens more often so `extends AtomicInteger` is better. Have the `AtomicReference` as instance field instead.

2018-05-09 10:33 UTC, akarnokd commented
Since no progress was made on this PR, I'm closing this in favor of #5979.

2018-05-09 10:33 UTC, closed without merging