Add delaySubscription() methods to Completable #5081
ReactiveX/RxJava pull request #6242
Opened 2018-10-10 10:50 UTC by soshial

Since Observable, Single already have `delaySubscription()`, but Completable doesn't, I added these methods to the code.

2018-10-10 11:11 UTC, akarnokd commented
Please [fix the mistakes](https://travis-ci.org/ReactiveX/RxJava/builds/439579164#L583) and add unit tests verifying these new methods.

2018-10-10 14:53 UTC, soshial commented
The code failed this test `ParamValidationCheckerTest` > checkCompletable FAILED.

Which should I better do:
1. put `ObjectHelper.verifyPositive(delay, "delay");` into all new methods of mine or
2. `return RxJavaPlugins.onAssembly(new CompletableTimer(Math.max(delay, 0L), unit, scheduler));` inside timer(...)

The first way looks more logical to me.

2018-10-10 14:57 UTC, akarnokd commented
Neither. Update the test to permit any integer like the other `delaySubscription` implementations, e.g., https://github.com/ReactiveX/RxJava/blob/2.x/src/test/java/io/reactivex/validators/ParamValidationCheckerTest.java#L149

2018-10-10 15:05 UTC, soshial commented
Got it. I will fix the tests. What about `timer()`, which way is correct:

https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/Completable.java#L909
or
https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/Observable.java#L3906
?

2018-10-10 15:09 UTC, akarnokd commented
You don't have to `max`, the one in `Observable` version is old and unnecessary.

2018-10-10 15:23 UTC, soshial commented
Should I remove it then from `Observable`?
Can I add `@since 2.3` to the new methods?

2018-10-10 16:28 UTC, akarnokd commented
> Should I remove max then from Observable?

Sure.

> Can I add @since 2.3 to the new methods?

Add `@since 2.2.3 - experimental` and `@Experimental`

2018-10-12 10:14 UTC, akarnokd requested changes
Please add unit tests that verify the expected behavior.

2018-10-12 14:13 UTC, akarnokd requested changes

2018-10-12 14:13 UTC, akarnokd commented on src/test/java/io/reactivex/internal/operators/completable/CompletableDelayTest.java
> +        verify(o, never()).onComplete();
No need to talk to  a mocked observer, TestObserver.assertEmpty() already verifies these.

2018-10-12 14:13 UTC, akarnokd commented on src/test/java/io/reactivex/internal/operators/completable/CompletableDelayTest.java
> +        verify(o, never()).onComplete();
No need to talk to  a mocked observer, TestObserver.assertEmpty() already verifies these.

2018-10-12 14:13 UTC, akarnokd commented on src/test/java/io/reactivex/internal/operators/completable/CompletableDelayTest.java
> +        verify(o, never()).onError(any(Throwable.class));
No need to talk to  a mocked observer, TestObserver.assertEmpty() already verifies these.

2018-10-12 14:13 UTC, akarnokd commented on src/test/java/io/reactivex/internal/operators/completable/CompletableDelayTest.java
> +        to.assertComplete();
`to.assertResult();` will check for the no-error condition.

2018-10-12 15:27 UTC, soshial commented
Thanks a lot for explanations! May I simply edit the last commit, because I gave a wrong title to the commit with tests (8233972)?

2018-10-12 15:51 UTC, akarnokd commented
Just commit the changes as fresh.

2018-10-15 11:06 UTC, akarnokd approved these changes

2018-10-15 16:25 UTC, artem-zinnatullin approved these changes

2018-10-15 16:25 UTC, artem-zinnatullin commented on src/test/java/io/reactivex/internal/operators/completable/CompletableDelayTest.java
> +        to.assertResult();
nit: here we rely just on completion signal, which as an implementation bug may be emitted by `delaySubscription` operator. I mean, right now there is obviously no bug, but in future if operator will be re-implemented, it might appear

Thus I'd recommend to add verifiable logic to the upstream, like `Completable.fromAction { if (!atomicBoolean.compareAndSet(false, true)) throw IllegalStateException() }`

and verify against that too:

```
to.assertResult()
assertTrue(atomicBoolean.get())
```

2018-10-15 16:27 UTC, vanniktech approved these changes

2018-10-18 09:19 UTC, akarnokd commented
@soshial do you want to address @artem-zinnatullin 's review?

2018-10-19 08:16 UTC, merged

2018-10-19 08:16 UTC, akarnokd commented on src/test/java/io/reactivex/internal/operators/completable/CompletableDelayTest.java
> +        to.assertResult();
I'll add the extra tests in a separate PR.

2018-10-19 16:40 UTC, soshial commented on src/test/java/io/reactivex/internal/operators/completable/CompletableDelayTest.java
> +        to.assertResult();
Thank you, @akarnokd