[Proposal] Remove CheckReturnValue on subscribe() overloads
ReactiveX/RxJava pull request #6304
Opened 2018-11-12 06:14 UTC by hzsweers

Proposal PR for my followup comment in #4878 at https://github.com/ReactiveX/RxJava/issues/4878#issuecomment-437763406

Will close if the discussion raised there still settles on keeping them, just wanted to show a PoC of what the change scope would look like for reference.

2018-11-12 07:14 UTC, vanniktech requested changes
I'd keep the annotation and in the rare cases suppress the warning. This annotation saved me more times than it harmed me.

2018-11-12 07:25 UTC, ZacSweers commented
Maybe you, but see the thread for plenty more cases where it's not useful :). Let's keep the discussion consolidated there

2018-11-12 07:33 UTC, akarnokd commented
This was discussed before. The no arg subscribe doesn't have it as being fire and forget, the rest do.

2018-11-12 07:42 UTC, hzsweers commented
That's not true actually

`Observable#subscribe(Consumer<? super T> onNext, Consumer<? super Throwable> onError, Action onComplete, Consumer<? super Disposable> onSubscribe)`

also requires it despite accepting an onSubscribe Consumer, and presumably that shouldn't require it by that logic either since a handling consumer is passed in. I understand it was discussed before, but I feel I've offered a good set of examples in the linked issue that highlight where the original reasoning has not accounted for.

2018-11-12 08:40 UTC, akarnokd commented
> also requires it despite accepting an onSubscribe Consumer

It is to be removed in 3.x: #5622

Also the issue here is a general conflict between one's individual coding style and the hard coded coding style of a library. So you either ignore warnings individually as Jake suggested or create a separate subscribe method/converter where you can ignore it once.

2018-11-12 08:57 UTC, hzsweers commented
> or create a separate subscribe method/converter in your project where you can ignore it once.

This seems like a really harsh stance to take :/. Any specific thoughts on the examples I raised?

2018-11-12 10:06 UTC, vanniktech commented
Talked with Zac offline and I understand his points now. We both have different valid ways of using RxJava and the annotation is a constraint that should not be enforced per se. 

I'd be willing to give up the annotation if we have proper open source toolings like Zac suggested that simulate the old behavior.

2018-11-12 10:16 UTC, hzsweers commented
And I'd be happy to contribute implementations (in existing or new projects) for error-prone and lint as a part of this :)

2018-11-12 12:56 UTC, akarnokd commented
This should have been part of some tooling all along, but then the lack of warnings out-of-box received by newcommers and beginners would have resulted in a lot of support requests. By the way, if tooling is created for this, it could have both the feature to add as well as remove via configuration for the entire project.

2018-11-12 16:56 UTC, artem-zinnatullin commented
my 2 cents: RxJava uses its own annotation for this, which means that it should be possible to disable it project (module) -wide without clashing with `@CheckReturnValue`s enforced by other libraries.

Thus, I'd rather keep it as is in RxJava (because there is value in it) and focus on tooling support for disabling such specific annotations.

2018-11-12 16:59 UTC, vanniktech commented
I think for Android Lint this might actually already be doable. For each issue there can be a regex defined. Might be enough to pass in the fully qualified name of the annotation.

2018-11-15 08:30 UTC, hzsweers commented
A custom annotation for this would work, but we'd probably have to deprecate the existing one vs. remove it since it's part of the public API right?

@vanniktech have a link/sample? I didn't know that was an option!

@akarnokd when you say

> it could have both the feature to add as well as remove via configuration for the entire project.

Could you elaborate a bit? I'm not sure I followed

2018-11-15 08:43 UTC, akarnokd commented
I meant like a config file:

```
@CheckReturnValue
+ io.reactivex.Flowable.subscribe()
- io.reactivex.Flowable.subscribe(io.reactivex.function.Consumer<? super T>)
```

Some tooling would check this file and apply the annotation virtually to the given method signature or ignore it.

2018-11-15 08:45 UTC, vanniktech commented
Something like that might work (haven't tried it out myself):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<lint>
  <issue id="CheckResult">
    <ignore regexp="io.reactivex.annotations.CheckReturnValue"/>
  </issue>
</lint>
```

2018-11-15 22:57 UTC, hzsweers commented
Let me see if ErrorProne's check allows for this. Unfortunately neither case covers the actual IDE tooling marking these (they don't read lint xml configurations and the intelliJ inspection doesn't support customization as far as I know)

2018-11-16 06:04 UTC, vanniktech commented
> they don't read lint xml configurations and the intelliJ inspection doesn't support customization as far as I know

I'm sure this can be fixed. Just like custom lint checks got fixed with 3.3

2018-11-16 07:29 UTC, hzsweers commented
Maybe. That was a bug and this would be a FR :). lint xml files are entirely a CLI implementation, and not part of the main lint API that the CLI and IDE plugins both implement

2018-11-16 09:32 UTC, hzsweers commented
Followup on error-prone - confirmed there's no way to configure this right now. I don't think focusing on disabling in other tooling is the right way to go about this, as it's much easier to enable custom tooling than it is to disable non-configurable existing tooling.

2018-11-16 09:42 UTC, artem-zinnatullin commented
One (me) could argue that changing a default behavior and requiring everyone who relies on it to reconfigure their tooling is also not great and hardly considerable as much easier :)

2018-11-16 11:35 UTC, hzsweers commented
That’s why I was proposing having new tooling available out the gate, so
anyone using lint or error-prone could just add these. If they’re already
using either of these, it should be a straightforward addition. If they
aren’t, then they likely weren’t using tooling for the old behavior anyway.

In either case - like I mentioned above, adding tooling is a matter of
configuration. Disabling tooling is nigh-impossible without forking
error-prone or lint to configure them in these cases. I’d rather err on the
side of flexibility than imposing something that basically can’t be
disabled.

On Fri, Nov 16, 2018 at 1:43 AM Artem Zinnatullin :slowpoke: <
notifications@github.com> wrote:

> One (me) could argue that changing a default behavior and requiring
> everyone who relies on it to reconfigure their tooling is also not great
> and hardly considerable as much easier :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ReactiveX/RxJava/pull/6304#issuecomment-439337685>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABTEvrc9yjIqKbiN6QBtQFJXz4KpAbfnks5uvojFgaJpZM4YZBXR>
> .
>

2018-11-16 13:44 UTC, vanniktech commented
> lint xml files are entirely a CLI implementation, and not part of the main lint API that the CLI and IDE plugins both implement

IntelliJ could read the lintConfig file from `android { lintOptions { .. } }`. Not seeing a problem with that

2018-11-16 20:45 UTC, hzsweers commented
The problem is that's a significant feature request for functionality that doesn't exist today right?

2018-11-17 10:09 UTC, vanniktech commented
Maybe. Maybe not. It's worth asking for nonetheless ;) - https://issuetracker.google.com/issues/119660763

2018-11-17 10:59 UTC, hzsweers commented
Even then, that still marries it to gradle android projects right?

2018-11-17 13:06 UTC, vanniktech commented
Probably yeah. Unless they find some universal way which would also work with other build systems. Feel free to suggest that in the issue since I'm only using Gradle.

2018-11-17 23:46 UTC, hzsweers commented
Yeah I think that's a good thing to file in general, but as a separate async thing. Mind if we continue with using a renamed annotation for rx?

2018-11-18 16:06 UTC, vanniktech commented
Yeah I'm in for having both (proper tooling support) and new tooling to flag this. 

You want to rename it so standard tools don't know the name and hence don't flag it, right? Custom checks like you proposed would read it then.

2018-11-19 09:10 UTC, hzsweers commented
Yeah rename, though we'd have to add a separate new one (and deprecate the existing one?) since it's part of the public API up to this point. Also - what should we call it? `PossiblyCheckReturnValue`? `RxCheckReturnValue`?

2018-11-19 16:16 UTC, vanniktech commented
I guess yeah but then in the end tools still need a way to exclude the current annotation since we can't remove it, right?

2018-11-19 16:37 UTC, hzsweers commented
Oh no I meant you can't delete the class. You can still remove it from the methods. I was as a actually thinking it's fine in it's other uses, and maybe just make a custom 2nd one for like `CheckDisposableReturnValue`

2018-11-19 17:04 UTC, vanniktech commented
Sounds like a good tradeoff.

2018-11-20 07:45 UTC, hzsweers commented
Rebased and switched over to a `OptionalCheckReturnValue`. Let me know if that works?

2018-11-20 08:12 UTC, vanniktech reviewed
It would. I'd like to see the tooling in place before we merge this though.

2018-11-20 08:18 UTC, hzsweers commented
I'll create a project for that now 👍

2018-11-20 17:10 UTC, vanniktech commented
You might have the possibility to reuse the existing Detector by creating your own and registering the new annotation and from there forward everything to the CheckResultDetector. That way you wouldn't need to duplicate all of the work.

I've also filed https://issuetracker.google.com/issues/119763072 - dunno if that's something they are willing to do though.

2018-11-22 00:01 UTC, hzsweers commented
I've created a project with working checkers for both here: https://github.com/hzsweers/rxjava2-optionalcheckreturnvalue-checkers

Going to try to get review from @vanniktech and a couple others separately, but they're mostly straightforward adaptation of existing checkers just for this new annotation

2018-11-23 21:19 UTC, vanniktech commented
Lint implementation looks good!

2018-11-23 21:26 UTC, JakeWharton commented
Still opposed to this. Makes the common case worse for the benefit of the uncommon case.

2018-11-23 21:52 UTC, hzsweers commented
Counterexample: RxLifecycle is nigh-ubiquitous in Android apps, would that still be considered an uncommon case?

2018-11-23 22:06 UTC, JakeWharton commented
I think you vastly overestimate its use and the use of a view model (not
the library which has nothing to do with view models, of course, the actual
pattern) means you only have a single subscription inside a lifecycle
removing the need to use it anyway.

On Fri, Nov 23, 2018, 4:52 PM Zac Sweers <notifications@github.com wrote:

> Counterexample: RxLifecycle is nigh-ubiquitous in Android apps, would that
> still be considered an uncommon case?
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/ReactiveX/RxJava/pull/6304#issuecomment-441322006>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAEEEZr6kAGcNaPSHNc-aF2P7_rRrvHsks5uyG4KgaJpZM4YZBXR>
> .
>

2018-11-23 22:13 UTC, hzsweers commented
Maybe! Unfortunately neither of us can prove that one way or the other. What about any of the other cases I mentioned in https://github.com/ReactiveX/RxJava/issues/4878#issuecomment-437767153? Especially considering RxJava is synchronous by default, it seems to me like there's quite a few "uncommon" cases. Maybe not enough to be "common", but it gets to a larger point of when static analysis tools should be imposed.

To me, hard checks like this should only be imposed in black-and-white situations, like a factory or cases where it's otherwise pointless to call that method without capturing the result. This seems far from black-and-white. On top of that, it's a check that's not configurable in any built-in error-prone/lint tooling (it's even hardcoded into lint today) that would otherwise enforce it.

I think I have an alternative idea, but I'd like to get thoughts on the above first

2018-12-03 03:46 UTC, closed without merging