Expand `Observable#debounce` and `Flowable#debounce` javadoc
ReactiveX/RxJava pull request #6377
Opened 2019-01-19 16:29 UTC by RomanWuattier

Mention that if the processing of a task takes too long
and a newer item arrives then the previous task will
get disposed interrupting a long running work.

Fixes: #6288

2019-01-19 16:43 UTC, akarnokd requested changes
The scheduler wording needs to be adapted to the particular overload.

2019-01-19 16:43 UTC, akarnokd commented on src/main/java/io/reactivex/Flowable.java
> +     * Delivery of the item after the grace period happens on the (default|given) {@code Scheduler}'s
You should adapt the text `(default|given)` based on the overload.

2019-01-19 16:43 UTC, akarnokd commented on src/main/java/io/reactivex/Flowable.java
> +     * Delivery of the item after the grace period happens on the (default|given) {@code Scheduler}'s
Here too.

2019-01-19 16:43 UTC, akarnokd commented on src/main/java/io/reactivex/Flowable.java
> +     * Delivery of the item after the grace period happens on the (default|given) {@code Scheduler}'s
Please adapt the text.

2019-01-19 16:43 UTC, akarnokd commented on src/main/java/io/reactivex/Observable.java
> +     * Delivery of the item after the grace period happens on the (default|given) {@code Scheduler}'s
Please adapt the text.

2019-01-19 16:43 UTC, akarnokd commented on src/main/java/io/reactivex/Observable.java
> +     * Delivery of the item after the grace period happens on the (default|given) {@code Scheduler}'s
Please adapt the text.

2019-01-19 16:43 UTC, akarnokd commented on src/main/java/io/reactivex/Observable.java
> +     * Delivery of the item after the grace period happens on the (default|given) {@code Scheduler}'s
Please adapt the text.

2019-01-19 16:55 UTC, RomanWuattier commented
Thanks for the review. Done.

2019-01-19 17:49 UTC, akarnokd commented on src/main/java/io/reactivex/Flowable.java
> +     * Delivery of the item after the grace period happens on the default {@code Scheduler}'s
Selector-based debounces don't have explicit threading so the wording should be adjusted:

```
The delivery of the item happens on the thread of the first {@code onNext} or {@code onComplete} signal of the generated {@code Publisher}|{@code ObservableSource} sequence,
which if takes too long, a newer item may arrive from the upstream, causing the
generated sequence to get cancelled|disposed, [...]
```

2019-01-19 17:49 UTC, akarnokd commented on src/main/java/io/reactivex/Observable.java
> +     * Delivery of the item after the grace period happens on the default {@code Scheduler}'s
Same as above.

2019-01-23 12:22 UTC, RomanWuattier commented
Thanks, the wording for selector-based debounces is updated.

2019-01-23 12:29 UTC, akarnokd approved these changes

2019-01-23 12:32 UTC, vanniktech approved these changes

2019-01-23 12:33 UTC, merged