Null check for BufferExactBoundedObserver
ReactiveX/RxJava pull request #6499
Opened 2019-06-12 14:55 UTC by JanKn

- [*] Please give a description about what and why you are contributing, even if it's trivial:

**Improve stability of the library.**
Other variants of the onComplete method include this Null check already, e.g. BufferExactUnboundedObserver, this check should fix the case when there is a race condition and buffer is already set to "null" by the time onComplete is called.

It is causing 0.1% crashes in our production app, this should improve stability of other apps too.

2019-06-12 15:07 UTC, akarnokd commented
I don't see how that scenario would be possible with just the exact buffer. Only the terminal events can set `buffer` to null and `run` is protected against a null buffer.
Aren't you using `PublishSubject` as well from multiple threads, competing for termination?

2019-06-12 15:08 UTC, akarnokd commented
Also an unit test demonstrating the presumed bug has been fixed is required.

2019-06-12 15:22 UTC, JanKn commented
To be honest, I am trying to simulate the scenario past day and a half.
Being it likely a race condition, it makes it difficult.
I will give Unit test a shot, if you have a sample Test for some other operator, which is testing similar case, I would appreaciate if you can point me there, thanks.

Our app uses some PublishSubjects, but we switched mostly to PublishRelay. The scenario with disposing from multiple threads is possible.
The production StackTrace we are seeing is this:

```
Fatal Exception: java.lang.NullPointerException: Null is not a valid element
       at io.reactivex.internal.queue.MpscLinkedQueue.offer(MpscLinkedQueue.java:60)
       at io.reactivex.internal.operators.observable.ObservableBufferTimed$BufferExactBoundedObserver.onComplete(ObservableBufferTimed.java:507)
       at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drainLoop(ObservableFlatMap.java:371)
       at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drain(ObservableFlatMap.java:326)
       at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onComplete(ObservableFlatMap.java:303)
       at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onComplete(BodyObservable.java:66)
       at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:51)
       at io.reactivex.Observable.subscribe(Observable.java:12268)
       at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
       at io.reactivex.Observable.subscribe(Observable.java:12268)
       at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
       at io.reactivex.Observable.subscribe(Observable.java:12268)
       at io.reactivex.internal.operators.observable.ObservableBufferTimed.subscribeActual(ObservableBufferTimed.java:66)
       at io.reactivex.Observable.subscribe(Observable.java:12268)
       at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
       at io.reactivex.Observable.subscribe(Observable.java:12268)
       at io.reactivex.internal.operators.observable.ObservableDoOnEach.subscribeActual(ObservableDoOnEach.java:42)
       at io.reactivex.Observable.subscribe(Observable.java:12268)
       at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
       at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:784)
```

2019-06-12 15:45 UTC, akarnokd commented
That code path should not lead to NPE. The only way for `buffer` to remain null is that the supplier fails, but then you should get an error signal. Otherwise, calling `onComplete` twice would result in NPE. The exact-boundary doesn't release the buffer upon disposing it, unlike the other implementation in that file.

2019-06-12 15:59 UTC, JanKn commented
I agree that it can be something wrong with the supplier. 
Another example: If supplier breaches the contract and calls onError (buffer is set to null) and then onComplete, which it should not, null gets into MprcLinkedQueue.offer:

```
...
    public boolean offer(final T e) {
        if (null == e) {
            throw new NullPointerException("Null is not a valid element");
        }
...  
```     
It does not happen super often given the size of the app, but it is still a concern.

2019-06-12 16:09 UTC, akarnokd commented
In that case, use a failing supplier with an empty source. No threading necessary. Also  the Flowable variant may be prone to the same issue. Could you check and fix that too?

2019-06-12 19:55 UTC, akarnokd requested changes

2019-06-12 19:55 UTC, akarnokd commented on src/main/java/io/reactivex/internal/operators/flowable/FlowableBufferTimed.java
> +import org.reactivestreams.Subscriber;
Please don't unroll star imports.

2019-06-12 19:55 UTC, akarnokd commented on src/test/java/io/reactivex/internal/operators/flowable/FlowableBufferTest.java
> +import org.junit.Before;
Please don't unroll star imports.

2019-06-12 19:55 UTC, akarnokd commented on src/test/java/io/reactivex/internal/operators/flowable/FlowableBufferTest.java
> +        FlowableBufferTimed.BufferExactBoundedSubscriber<Integer, List<Integer>> buf = new FlowableBufferTimed.BufferExactBoundedSubscriber<Integer, List<Integer>>(observer, ArrayListSupplier.<Intege
The list supplier should fail, calling onError and onCompleted this way is just a plain protocol violation.

Do something this instead:

```java
Flowable.empty()
.buffer(10, 10, TimeUnit.SECONDS, Schedulers.computation(), new Callable<List<Object>>() {
    @Override public void call() {
        throw new TestException();
    }
})
.test()
.awaitDone(5, TimeUnit.SECONDS)
.assertFailure(TestException.class)
;
```

2019-06-12 19:55 UTC, akarnokd commented on src/test/java/io/reactivex/internal/operators/observable/ObservableBufferTest.java
> +        Scheduler.Worker w = new TestScheduler().createWorker();
The list supplier should fail, calling onError and onCompleted this way is just a plain protocol violation.

Do something this instead:

```java
Observable.empty()
.buffer(10, 10, TimeUnit.SECONDS, Schedulers.computation(), new Callable<List<Object>>() {
    @Override public void call() {
        throw new TestException();
    }
})
.test()
.awaitDone(5, TimeUnit.SECONDS)
.assertFailure(TestException.class)
;
```

2019-06-13 11:49 UTC, akarnokd approved these changes

2019-06-13 12:17 UTC, JanKn commented
Hi, 
thank you for the test sample, that helped a lot, I just had to hit the right condition.
I think we can merge this change now.
When do you expect a release containing this?

2019-06-13 12:19 UTC, akarnokd commented
I usually wait for @vanniktech's review, then if you think this is urgent, we can release soon after.

2019-06-17 12:43 UTC, merged

2019-06-17 12:52 UTC, vanniktech reviewed
Whops. Totally lost track of this! LGTM!