[WIP] 3.x: Introduce property rx3.scheduler.drift-use-nanotime
ReactiveX/RxJava pull request #7169
Opened 2021-01-27 22:10 UTC by SergejIsbrecht

Fixes #7168

2021-01-27 22:14 UTC, SergejIsbrecht commented
@akarnokd ,

I got a problem, when I try to test the code, because when the class is loaded, one can not change set variable:

`private static final String DRIFT_USE_NANOTIME = "rx3.scheduler.drift-use-nanotime"; 

Resolution:
* no tests
* define a own test set, which tests the nanoTime use-case and configure this test-src-set to run each class in a new JVM
* find a Junit-runner which loads the test-classes via a own ClassLoader
* remove "final" for `DRIFT_USE_NANOTIME` and set it for testing, which might not be desirable, because it can be changed later.

What are your thoughts on this issue regarding testing?

2021-01-27 22:17 UTC, akarnokd requested changes

2021-01-27 22:17 UTC, akarnokd commented on src/main/java/io/reactivex/rxjava3/core/Scheduler.java
> +    static final boolean IS_DRIFT_USE_NANOTIME = Boolean.getBoolean("rx3.scheduler.drift-use-nanotime");
This can't be tested because the class gets initialized much earlier. Please drop the `final`. Also please document the field with Javadocs.

2021-01-28 06:14 UTC, akarnokd reviewed
Since this affects now(), let's call the property just `rx3.scheduler.use-nanotime`.

2021-01-28 08:52 UTC, akarnokd approved these changes

2021-01-28 13:12 UTC, SergejIsbrecht commented
@akarnokd , should I change the commit message as-well?

2021-01-28 13:17 UTC, akarnokd commented
No need for that.

2021-01-28 15:27 UTC, vanniktech approved these changes

2021-01-28 15:29 UTC, merged