Fix assert message format
ReactiveX/RxJava pull request #7351
Opened 2021-10-13 21:19 UTC by keytronic

This PR is related to a previous one I opened: #7345

I've made a mistake when I tested regex because `\nexpected: (.*)\n\s*got: (.*)` does not allow prefixes.
I changed assert messages to use suffixes instead of prefixes.

Sorry about that !

2021-10-13 21:42 UTC, akarnokd approved these changes

2021-10-13 22:35 UTC, vanniktech approved these changes
Should the error messages be tested against that regex to ensure that it works?

2021-10-14 09:54 UTC, akarnokd requested changes
Indeed, please add tests that verify the error messages against the intended regex.

2021-10-14 14:48 UTC, akarnokd requested changes

2021-10-14 14:48 UTC, akarnokd commented on src/test/java/io/reactivex/rxjava3/observers/TestObserverTest.java
> +        assertThrowsWithMessageMatchRegex(ASSERT_MESSAGE_REGEX, AssertionError.class, () -> {
Please don't change this to the regex check but introduce separate tests.

2021-10-14 16:19 UTC, keytronic commented on src/test/java/io/reactivex/rxjava3/observers/TestObserverTest.java
> +        assertThrowsWithMessageMatchRegex(ASSERT_MESSAGE_REGEX, AssertionError.class, () -> {
Good point. I fixed tests 👍

2021-10-14 16:24 UTC, akarnokd approved these changes

2021-10-14 17:28 UTC, vanniktech approved these changes

2021-10-14 17:30 UTC, merged

2022-01-30 18:41 UTC, Akhenaton27 approved these changes