Adding onDropped callback to throttleLast as a part of #7458
ReactiveX/RxJava pull request #7488
Opened 2022-11-30 21:07 UTC by Desislav-Petrov

Adding onDropped callback for throttleLast - #7458

2022-11-30 21:19 UTC, akarnokd requested changes

2022-11-30 21:19 UTC, akarnokd commented on src/main/java/io/reactivex/rxjava3/core/Flowable.java
> +    public final Flowable<T> sample(long period, @NonNull TimeUnit unit, @NonNull Scheduler scheduler, boolean emitLast, @NonNull Consumer<T> onDropped) {
Please only add this overload to `sample` and not the others.

2022-11-30 21:19 UTC, akarnokd commented on src/main/java/io/reactivex/rxjava3/core/Flowable.java
> +    public final Flowable<T> throttleLast(long intervalDuration, @NonNull TimeUnit unit, @NonNull Scheduler scheduler, @NonNull Consumer<T> onDropped) {
Please only add this `throttleLast` overload and no other.

2022-11-30 21:19 UTC, akarnokd commented on src/main/java/io/reactivex/rxjava3/core/Observable.java
> +    public final Observable<T> sample(long period, @NonNull TimeUnit unit, @NonNull Scheduler scheduler, @NonNull Consumer<T> onDropped) {
Please only add this `sample` overload.

2022-11-30 21:19 UTC, akarnokd commented on src/main/java/io/reactivex/rxjava3/core/Observable.java
> +    public final Observable<T> throttleLast(long intervalDuration, @NonNull TimeUnit unit, @NonNull Scheduler scheduler, @NonNull Consumer<T> onDropped) {
Please only add this `throttleLast` overload.

2022-11-30 21:19 UTC, akarnokd commented on src/main/java/io/reactivex/rxjava3/core/Observable.java
> +     *  <dt><b>Scheduler:</b></dt>&
Unnecessary change.

2022-12-02 20:59 UTC, Desislav-Petrov commented
hi @akarnokd thx for the review - all addressed

2022-12-02 21:05 UTC, akarnokd approved these changes

2022-12-03 13:21 UTC, merged